apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-tekton
spec:
  destination:
    namespace: team2
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: true
    path: argocd/team2/tekton
    repoURL: https://github.com/jwimsingues/tekton-argocd-demo.git
    targetRevision: main
  syncPolicy:
    automated:
      # Put false to prune so we can keep the history of PipelineRun
      prune: false
      # Should be false because if not your PipelineRun will then be killed
      selfHeal: false
