apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-vote-ui
spec:
  destination:
    namespace: team2
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: true
    path: argocd/team2/vote-ui
    repoURL: https://github.com/jwimsingues/tekton-argocd-demo.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
